import type { Metadata } from "next";
import { Calistoga, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

const calistoga = Calistoga({
  subsets: ["latin"],
  variable: "--font-display",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${calistoga.variable}`}
    >
      <body className={`flex flex-col min-h-screen font-sans antialiased`}>
        <header>
          <Navbar />
        </header>

        <main className="flex-1 flex justify-center items-center">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
